name: flutter_application_5
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.1
  http: ^0.13.4
  shared_preferences: ^2.1.2
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  flutter_speed_dial: ^7.0.0
  image_cropper: ^4.0.1
  image_picker: ^0.8.7+5
  multi_image_picker: ^4.8.0+1
  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/eula.txt
